//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_atendimento
    {
        public int atendimento_id { get; set; }
        public System.DateTime atendimento_data { get; set; }
        public decimal atendimento_valor { get; set; }
        public string atendimento_historia { get; set; }
        public int usuario_id { get; set; }
        public int servico_id { get; set; }
        public int cliente_id { get; set; }
        public int colaborador_id { get; set; }
    
        public virtual tb_cliente tb_cliente { get; set; }
        public virtual tb_colaborador tb_colaborador { get; set; }
        public virtual tb_servico tb_servico { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
