//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_colaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_colaborador()
        {
            this.tb_atendimento = new HashSet<tb_atendimento>();
        }
    
        public int colaborador_id { get; set; }
        public string colaborador_nome { get; set; }
        public string colaborador_funcao { get; set; }
        public int usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_atendimento> tb_atendimento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
