//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_cliente()
        {
            this.tb_atendimento = new HashSet<tb_atendimento>();
        }
    
        public int cliente_id { get; set; }
        public string cliente_nomeCompleto { get; set; }
        public System.DateTime cliente_dataNascimento { get; set; }
        public string cliente_nomeMae { get; set; }
        public string cliente_cpf { get; set; }
        public string cliente_nomePai { get; set; }
        public short cliente_estadoCivil { get; set; }
        public string cliente_nomeConjuge { get; set; }
        public string cliente_email { get; set; }
        public string cliente_telefone { get; set; }
        public string cliente_cep { get; set; }
        public string cliente_endereco { get; set; }
        public string cliente_numero { get; set; }
        public string cliente_bairro { get; set; }
        public string cliente_cidade { get; set; }
        public int usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_atendimento> tb_atendimento { get; set; }
        public virtual tb_usuario tb_usuario { get; set; }
    }
}
